/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import modelo.Numero;

/**
 *
 * @author Rodrigo
 * @version 1.0.2 Phil Collins
 * @since 22/03/2019 23:19
 */
public class GUIBhaskara extends javax.swing.JFrame {

    /**
     * Creates new form GUIBhaskara
     */
    public GUIBhaskara() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgOpcao = new javax.swing.ButtonGroup();
        jlpBhaskara = new javax.swing.JLayeredPane();
        jlA = new javax.swing.JLabel();
        jlB = new javax.swing.JLabel();
        jlC = new javax.swing.JLabel();
        jtA = new javax.swing.JTextField();
        jtB = new javax.swing.JTextField();
        jtC = new javax.swing.JTextField();
        jlpOpcao = new javax.swing.JLayeredPane();
        jlOpcao = new javax.swing.JLabel();
        jrJOptionPane = new javax.swing.JRadioButton();
        jrJlabel = new javax.swing.JRadioButton();
        jrAmbos = new javax.swing.JRadioButton();
        jbCalcular = new javax.swing.JButton();
        jlpResposta = new javax.swing.JLayeredPane();
        jlResposta = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtResposta = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bhaskara");

        jlpBhaskara.setBorder(javax.swing.BorderFactory.createTitledBorder("Bhaskara"));

        jlA.setText("a");

        jlB.setText("b");

        jlC.setText("c");

        jtA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtAKeyPressed(evt);
            }
        });

        jtB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtBKeyPressed(evt);
            }
        });

        jtC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtCKeyPressed(evt);
            }
        });

        jlpBhaskara.setLayer(jlA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpBhaskara.setLayer(jlB, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpBhaskara.setLayer(jlC, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpBhaskara.setLayer(jtA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpBhaskara.setLayer(jtB, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpBhaskara.setLayer(jtC, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpBhaskaraLayout = new javax.swing.GroupLayout(jlpBhaskara);
        jlpBhaskara.setLayout(jlpBhaskaraLayout);
        jlpBhaskaraLayout.setHorizontalGroup(
            jlpBhaskaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpBhaskaraLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jlpBhaskaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlA)
                    .addComponent(jlB)
                    .addComponent(jlC))
                .addGap(18, 18, 18)
                .addGroup(jlpBhaskaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtC)
                    .addComponent(jtB, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtA, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(24, 24, 24))
        );
        jlpBhaskaraLayout.setVerticalGroup(
            jlpBhaskaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpBhaskaraLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jlpBhaskaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlA))
                .addGap(32, 32, 32)
                .addGroup(jlpBhaskaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlB)
                    .addComponent(jtB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jlpBhaskaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlC)
                    .addComponent(jtC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        jlpOpcao.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlOpcao.setText("Opção:");

        bgOpcao.add(jrJOptionPane);
        jrJOptionPane.setText("Mostrar JOPtionPane");
        jrJOptionPane.setActionCommand("joptionpane");
        jrJOptionPane.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrJOptionPaneKeyPressed(evt);
            }
        });

        bgOpcao.add(jrJlabel);
        jrJlabel.setText("MostrarJlabel");
        jrJlabel.setActionCommand("jlabel");
        jrJlabel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrJlabelKeyPressed(evt);
            }
        });

        bgOpcao.add(jrAmbos);
        jrAmbos.setText("Mostrar em ambos");
        jrAmbos.setActionCommand("ambos");
        jrAmbos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrAmbosKeyPressed(evt);
            }
        });

        jbCalcular.setText("Calcular");
        jbCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCalcularActionPerformed(evt);
            }
        });
        jbCalcular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbCalcularKeyPressed(evt);
            }
        });

        jlpOpcao.setLayer(jlOpcao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpOpcao.setLayer(jrJOptionPane, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpOpcao.setLayer(jrJlabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpOpcao.setLayer(jrAmbos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpOpcao.setLayer(jbCalcular, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpOpcaoLayout = new javax.swing.GroupLayout(jlpOpcao);
        jlpOpcao.setLayout(jlpOpcaoLayout);
        jlpOpcaoLayout.setHorizontalGroup(
            jlpOpcaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpOpcaoLayout.createSequentialGroup()
                .addGroup(jlpOpcaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpOpcaoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlOpcao))
                    .addGroup(jlpOpcaoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jlpOpcaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrJlabel)
                            .addComponent(jrJOptionPane)
                            .addComponent(jrAmbos)))
                    .addGroup(jlpOpcaoLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jbCalcular)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jlpOpcaoLayout.setVerticalGroup(
            jlpOpcaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpOpcaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlOpcao)
                .addGap(18, 18, 18)
                .addComponent(jrJOptionPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrJlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrAmbos)
                .addGap(18, 18, 18)
                .addComponent(jbCalcular)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jlpResposta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlResposta.setText("Resposta:");

        jtResposta.setColumns(20);
        jtResposta.setRows(5);
        jScrollPane1.setViewportView(jtResposta);

        jlpResposta.setLayer(jlResposta, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpResposta.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpRespostaLayout = new javax.swing.GroupLayout(jlpResposta);
        jlpResposta.setLayout(jlpRespostaLayout);
        jlpRespostaLayout.setHorizontalGroup(
            jlpRespostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpRespostaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlResposta)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addContainerGap())
        );
        jlpRespostaLayout.setVerticalGroup(
            jlpRespostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpRespostaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpRespostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlResposta))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlpResposta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlpBhaskara)
                        .addGap(18, 18, 18)
                        .addComponent(jlpOpcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlpBhaskara)
                    .addComponent(jlpOpcao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlpResposta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * metodo para setar os dados e exibir a resposta
     */
    private void calcular(){
        Numero n = new Numero();
        
        //entrada dos dados
        n.setA(Integer.parseInt(jtA.getText()));
        n.setB(Integer.parseInt(jtB.getText()));
        n.setC(Integer.parseInt(jtC.getText()));
        
        String exibicao = bgOpcao.getSelection().getActionCommand();
        
        jtResposta.setText(n.selecionarSaida(exibicao, rootPane));
    }
    
    /**
     * metodo para limpar os campos de texto e selecao
     */
    private void limpar(){
        jtA.setText("");
        jtB.setText("");
        jtC.setText("");
        bgOpcao.clearSelection();
        
        jtA.requestFocus();
    }

    /**
     * 
     * @param evt clique no botao calcular
     */
    private void jbCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCalcularActionPerformed
        calcular();
        limpar();
    }//GEN-LAST:event_jbCalcularActionPerformed

    /**
     * 
     * @param evt enter no botao calcular
     */
    private void jbCalcularKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbCalcularKeyPressed
        switch(evt.getKeyCode()){
            case KeyEvent.VK_ENTER:
                calcular();
                limpar();
            case KeyEvent.VK_UP:
                jrAmbos.grabFocus();
        }
    }//GEN-LAST:event_jbCalcularKeyPressed

    /**
     * avanca para o proximo
     * @param evt enter no campo de texto
     */
    private void jtAKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtAKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jtB.grabFocus();
        }
    }//GEN-LAST:event_jtAKeyPressed

    /**
     * avanca para o proximo
     * @param evt enter no campo de texto
     */
    private void jtBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtBKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jtC.grabFocus();
        }
    }//GEN-LAST:event_jtBKeyPressed

    /**
     * avanca para o proximo
     * @param evt enter no campo de texto
     */
    private void jtCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtCKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jrJOptionPane.grabFocus();
        }
    }//GEN-LAST:event_jtCKeyPressed

    /**
     * calcula ou avanca para o proximo radiobutton
     * @param evt enter ou seta para baixo no campo de texto
     */
    private void jrJOptionPaneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrJOptionPaneKeyPressed
        switch(evt.getKeyCode()){
            case KeyEvent.VK_ENTER:
                calcular();
                limpar();
            case KeyEvent.VK_DOWN:
                jrJlabel.grabFocus();
        }
    }//GEN-LAST:event_jrJOptionPaneKeyPressed

    /**
     * calcula ou avanca para o proximo radiobutton
     * @param evt enter, seta para baixo ou para cima no campo de texto
     */
    private void jrJlabelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrJlabelKeyPressed
        switch(evt.getKeyCode()){
            case KeyEvent.VK_ENTER:
                calcular();
                limpar();
            case KeyEvent.VK_UP:
                jrJOptionPane.grabFocus();
            case KeyEvent.VK_DOWN:
                jrAmbos.grabFocus();
        }
    }//GEN-LAST:event_jrJlabelKeyPressed

    /**
     * calcula ou avanca para o proximo radiobutton
     * @param evt enter, seta para baixo ou para cima no campo de texto
     */
    private void jrAmbosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrAmbosKeyPressed
        switch(evt.getKeyCode()){
            case KeyEvent.VK_ENTER:
                calcular();
                limpar();
            case KeyEvent.VK_UP:
                jrJlabel.grabFocus();
            case KeyEvent.VK_DOWN:
                jbCalcular.grabFocus();
        }
    }//GEN-LAST:event_jrAmbosKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIBhaskara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIBhaskara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIBhaskara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIBhaskara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIBhaskara().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgOpcao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbCalcular;
    private javax.swing.JLabel jlA;
    private javax.swing.JLabel jlB;
    private javax.swing.JLabel jlC;
    private javax.swing.JLabel jlOpcao;
    private javax.swing.JLabel jlResposta;
    private javax.swing.JLayeredPane jlpBhaskara;
    private javax.swing.JLayeredPane jlpOpcao;
    private javax.swing.JLayeredPane jlpResposta;
    private javax.swing.JRadioButton jrAmbos;
    private javax.swing.JRadioButton jrJOptionPane;
    private javax.swing.JRadioButton jrJlabel;
    private javax.swing.JTextField jtA;
    private javax.swing.JTextField jtB;
    private javax.swing.JTextField jtC;
    private javax.swing.JTextArea jtResposta;
    // End of variables declaration//GEN-END:variables
}
